language: php
php:
  - "5.4"
  - "5.3"
sudo: false
before_script:
  - export PATH=~/.composer/vendor/bin/:$PATH
  - mysql -uroot -e "CREATE DATABASE test;"
  - composer install --dev --no-interaction ;
  - ./scripts/generate-mo --quiet
script:
  - ./vendor/bin/phpunit --configuration phpunit.xml.nocoverage
cache:
  directories:
    - $HOME/.composer/cache/
